# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='chinook.Artist'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
