# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0002_auto_20170712_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
