# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0003_auto_20170713_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='chinook.Artist'),
        ),
    ]
