# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0004_auto_20170716_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='support_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chinook.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chinook.Employee'),
        ),
    ]
