# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0007_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chinook.Track'),
        ),
    ]
