# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0008_auto_20170727_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='track',
        ),
        migrations.DeleteModel(
            name='Invoiceline',
        ),
    ]
