# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0009_auto_20170727_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
