# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0010_auto_20170727_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='support_rep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reports_to',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
